# Generated by Django 4.1 on 2022-11-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_commentcrm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата заказа'),
        ),
    ]
